name: Build and Test
on:
  push:
    branches: [ 'master' ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
      - uses: actions/checkout@v4
        name: Clone debezium module repo
        with:
          repository: csaude/openmrs-module-debezium
          path: openmrs-module-debezium
      - name: Install debezium module
        working-directory: ./openmrs-module-debezium
        run: mvn install
      - uses: actions/checkout@v4
        name: Clone MPI module repo
      - name: Build and test with maven
        run: mvn test --no-transfer-progress -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
